/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import helper.CwqHelper;

import java.awt.event.ItemEvent;

import data.Constant;

/**
 *
 * @author  __USER__
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		initType();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jp_main = new javax.swing.JPanel();
		cb_type = new javax.swing.JComboBox();
		et_page = new javax.swing.JTextField();
		btn_start = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		cb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		cb_type.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cb_typeItemStateChanged(evt);
			}
		});

		et_page.setColumns(5);
		et_page.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				et_pageActionPerformed(evt);
			}
		});

		btn_start.setText("\u5f00\u59cb");
		btn_start.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_startActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jp_mainLayout = new javax.swing.GroupLayout(
				jp_main);
		jp_main.setLayout(jp_mainLayout);
		jp_mainLayout
				.setHorizontalGroup(jp_mainLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_mainLayout
										.createSequentialGroup()
										.addGap(23, 23, 23)
										.addComponent(
												cb_type,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(101, 101, 101)
										.addComponent(
												et_page,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												106, Short.MAX_VALUE)
										.addComponent(btn_start)
										.addGap(28, 28, 28)));
		jp_mainLayout
				.setVerticalGroup(jp_mainLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jp_mainLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jp_mainLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																cb_type,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(btn_start)
														.addComponent(
																et_page,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(240, Short.MAX_VALUE)));

		jMenu1.setText("\u6570\u636e\u6e90");

		jMenuItem1.setText("\u57ce\u5916\u5708");
		jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenuItem1MouseClicked(evt);
			}
		});
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_main, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_main, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {
		start();
	}

	private void cb_typeItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			int index = cb_type.getSelectedIndex();
			type_id = Constant.LIST_TYPE_ID[index] + "";
			currentType = cb_type.getSelectedIndex() + 1 + "";
			System.out.println("type = " + currentType + ", type_id = " + type_id);
		}
	}

	private void et_pageActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {

		CwqJpanel jp_cwq = new CwqJpanel();
		add(jp_cwq);
		jp_main.setVisible(false);
		jp_cwq.setVisible(true);

	}

	private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {

	}

	private void start() {
		CwqHelper helper = new CwqHelper();
		helper.setId(currentType);
		type_id = Constant.LIST_TYPE_ID[cb_type.getSelectedIndex()] + "";
		helper.setTypeId(type_id);
		helper.setPage(Integer.valueOf(et_page.getText()));
		if(helper.login()) {
			helper.getWxData();
		}
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void initType() {
		cb_type.setModel(new javax.swing.DefaultComboBoxModel(
				Constant.LIST_TYPE));
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_start;
	private javax.swing.JComboBox cb_type;
	private javax.swing.JTextField et_page;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JPanel jp_main;
	// End of variables declaration//GEN-END:variables

	private String currentType;
	private String type_id;
}