/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import helper.CwqHelper;

import java.awt.event.ItemEvent;

import javax.crypto.spec.IvParameterSpec;

import utils.FrameUtil;

import data.Constant;

/**
 *
 * @author  __USER__
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		initType();
		FrameUtil.initWindows(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jp_main = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		cb_type = new javax.swing.JComboBox();
		et_page = new javax.swing.JTextField();
		btn_start = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		item_cwq = new javax.swing.JMenuItem();
		item_wx = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(500, 300));
		setResizable(false);

		jp_main.setMaximumSize(new java.awt.Dimension(500, 300));
		jp_main.setMinimumSize(new java.awt.Dimension(500, 300));
		jp_main.setLayout(new java.awt.GridLayout());

		cb_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		cb_type.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cb_typeItemStateChanged(evt);
			}
		});

		et_page.setColumns(5);

		btn_start.setText("\u5f00\u59cb");
		btn_start.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_startActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap(122, Short.MAX_VALUE)
						.addComponent(cb_type,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(66, 66, 66)
						.addComponent(et_page,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(69, 69, 69).addComponent(btn_start)
						.addGap(88, 88, 88)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(64,
																				64,
																				64)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								et_page,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								btn_start)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(46,
																				46,
																				46)
																		.addComponent(
																				cb_type,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(313, Short.MAX_VALUE)));

		jp_main.add(jPanel1);

		jMenu1.setText("\u529f\u80fd");

		item_cwq.setText("\u57ce\u5916\u5708");
		item_cwq.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				item_cwqActionPerformed(evt);
			}
		});
		jMenu1.add(item_cwq);

		item_wx.setText("\u5fae\u4fe1");
		item_wx.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				item_wxActionPerformed(evt);
			}
		});
		jMenu1.add(item_wx);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_main, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_main, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void item_wxActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {
		start();
	}

	private void cb_typeItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			int index = cb_type.getSelectedIndex();
			type_id = Constant.LIST_TYPE_ID[index] + "";
			currentType = cb_type.getSelectedIndex() + 1 + "";
			System.out.println("type = " + currentType + ", type_id = "
					+ type_id);
		}
	}

	void item_cwqActionPerformed(java.awt.event.ActionEvent evt) {
		CwqJpanel jp_cwq = new CwqJpanel();
		jp_cwq.setVisible(true);
		jp_main.removeAll();
		jp_main.add(jp_cwq);
		this.invalidate();
		this.repaint();
	}

	private void start() {
		CwqHelper helper = new CwqHelper();
		helper.setId(currentType);
		type_id = Constant.LIST_TYPE_ID[cb_type.getSelectedIndex()] + "";
		helper.setTypeId(type_id);
		helper.setPage(Integer.valueOf(et_page.getText()));
		if (helper.login()) {
			helper.getWxData();
		}
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void initType() {
		cb_type.setModel(new javax.swing.DefaultComboBoxModel(
				Constant.LIST_TYPE));
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_start;
	private javax.swing.JComboBox cb_type;
	private javax.swing.JTextField et_page;
	private javax.swing.JMenuItem item_cwq;
	private javax.swing.JMenuItem item_wx;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jp_main;
	// End of variables declaration//GEN-END:variables

	private String currentType;
	private String type_id;
}