/*
 * WXJpanel.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.io.IOException;

import helper.WXhelper;

import javax.swing.JFrame;

import utils.FrameUtil;

/**
 *
 * @author  __USER__
 */
public class WXJpanel extends javax.swing.JPanel {

	/** Creates new form WXJpanel */
	public WXJpanel(JFrame frame) {
		initComponents();
		FrameUtil.initWindows(frame);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btn_start = new javax.swing.JButton();

		btn_start.setText("\u70b9\u51fb\u83b7\u53d6\u9605\u8bfb\u6570");
		btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_startMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(143, 143, 143)
						.addComponent(btn_start)
						.addContainerGap(140, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(122, 122, 122)
						.addComponent(btn_start)
						.addContainerGap(155, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {
		start();
	}
	
	private void start() {
		try {
			WXhelper.getSearchList("a");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btn_start;
	// End of variables declaration//GEN-END:variables

}